name: Dodatek 1

on:
  push:
    branches: [ master ]

jobs:

  build-push-images:
    name: Build image + send on Dockerhub
    runs-on: ubuntu-latest

    steps:
    #Akcja do sprawdzania kodu
    - name: Checkout code
      uses: actions/checkout@v2
      
    #Akcja do instalacji QEMU
    - name: Setup QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      
    #Akcja do instalacji buildx
    - name: Buildx setup
      id: buildx
      uses: docker/setup-buildx-action@v1
      
 #   #Logowanie do docker hub za pomocą secretów
 #   - name: Login to DockerHub
 #     uses: docker/login-action@v1 
 #     with:
 #       username: ${{ secrets.DH_USERNAME }}
 #       password: ${{ secrets.DH_KEY }}
      
 # #Akcja do budowania obrazów i publikowania ich na GHCR.
 # #Obrazy publikowane są na zad1_dod1:serwer.
 # #Opcja z eksportem cache.
 #   - name: Build and push
 #     id: docker_build
 #     uses: docker/build-push-action@v2
 #     with:
 #         context: ./
 #         platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
 #         file: ./Dockerfile
 #         push: true
 #         tags: scoutertf2/zad1:dod1
 #         cache-from: type=registry,ref=scoutertf2/zad1:dod1
 #         cache-to: type=inline
      
    #Akcja do logowania na Github Container Registry.
    #Zmienna github.actor zawiera nazwę użytkownika.
    #Hasło pobieranie jest z secretu GIT_HUB_CON_REG_TOKEN
    - name: Login on Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: W-Sarnowski
        password: ${{ secrets.GIT_HUB_CON_REG_TOKEN }}
        
    #Akcja do budowania obrazów i publikowania ich na GHCR.
    #Obrazy publikowane są na zad1_dod1:serwer.
    #Opcja z eksportem cache.
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/scoutertf2/zad1:dod1
          cache-from: type=registry,ref=ghcr.io/scoutertf2/zad1:dod1
          cache-to: type=inline
